name: fetch-newgrad-job-postings

on:
  schedule:
    # Runs at 11 AM, 3 PM, 7 PM, 11 PM EST (16:00, 20:00, 00:00, 04:00 UTC)
    - cron: '0 16,20 * * *'  # 11 AM EST, 3 PM EST
    - cron: '0 0,4 * * *'    # 7 PM EST, 11 PM EST (next day in UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  post-newgrad-jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.ADMIN_PAT }} 
      
      - name: Set Up Python For Script
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Installing Dependencies
        run: |
          pip install requests PyGithub python-dotenv
      
      - name: Run the new grad job posting script
        env:
          TEST_MODE: 'true'  # Remove this line or set to 'false' for production
          DISCORD_WEBHOOK_URL_NEWGRAD: ${{ secrets.DISCORD_WEBHOOK_URL_NEWGRAD }}
          DISCORD_WEBHOOK_URL_NEWGRAD_TEST: ${{ secrets.DISCORD_WEBHOOK_URL_NEWGRAD_TEST }}
        run: python scripts/fetch-newgrad-jobs.py
      
      - name: Commit Updated JSON File
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated posted new grad jobs"
          file_pattern: "posted_jobs_newgrad.json"
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
